services:
    php:
        build: ./docker/php
        container_name: ${PROJECT_NAME}_php
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:1.27
        container_name: ${PROJECT_NAME}_nginx
        ports:
            - "127.0.0.1:${NGINX_PORT}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: postgres:16
        container_name: ${PROJECT_NAME}_db
        environment:
            POSTGRES_DB: ${PROJECT_NAME}
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./docker/db_data:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:${DATABASE_PORT}:5432
